name: Deploy to Firebase Hosting

# deployブランチにプッシュされたときにFirebase HostingにデプロイするGitHub Actionsの設定
on:
  push:
    branches:
      - deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create firebaserc file
        run: |
          echo '{ "projects": { "default": "${{ secrets.PROJECT_ID }}" } }' > .firebaserc

      - name: Generate Firebase Config
        run: |
          # ディレクトリが存在することを確認
          mkdir -p public/js

          # firebase-config.js を作成し、Secretsを埋め込む
          cat <<EOF > public/js/firebase-config.js
          export const firebaseConfig = {
            apiKey: "${{ secrets.API_KEY }}",
            authDomain: "${{ secrets.AUTH_DOMAIN }}",
            projectId: "${{ secrets.PROJECT_ID }}",
            storageBucket: "${{ secrets.STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.APP_ID }}",
            measurementId: "${{ secrets.MEASUREMENT_ID }}"
          };

          export const recaptchaSiteKey = "${{ secrets.RECAPTCHA_SITE_KEY }}";
          EOF

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live
          projectId: walletwise-abc97
