name: Deploy to Firebase Hosting

# deployブランチにプッシュされたときにFirebase HostingにデプロイするGitHub Actionsの設定
on:
  push:
    branches:
      - deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create firebaserc file
        run: |
          echo '{ "projects": { "default": "${{ secrets.PROJECT_ID }}" } }' > .firebaserc

      - name: Populate Firebase config
        run: |
          sed -i 's|__API_KEY__|${{ secrets.API_KEY }}|g' public/js/firebase.template.js
          sed -i 's|__AUTH_DOMAIN__|${{ secrets.AUTH_DOMAIN }}|g' public/js/firebase.template.js
          sed -i 's|__PROJECT_ID__|${{ secrets.PROJECT_ID }}|g' public/js/firebase.template.js
          sed -i 's|__STORAGE_BUCKET__|${{ secrets.STORAGE_BUCKET }}|g' public/js/firebase.template.js
          sed -i 's|__MESSAGING_SENDER_ID__|${{ secrets.MESSAGING_SENDER_ID }}|g' public/js/firebase.template.js
          sed -i 's|__APP_ID__|${{ secrets.APP_ID }}|g' public/js/firebase.template.js
          sed -i 's|__MEASUREMENT_ID__|${{ secrets.MEASUREMENT_ID }}|g' public/js/firebase.template.js
          sed -i 's|__RECAPTCHA_SITE_KEY__|${{ secrets.RECAPTCHA_SITE_KEY }}|g' public/js/firebase.template.js
          mv public/js/firebase.template.js public/js/firebase.js

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live
          projectId: walletwise-abc97
