name: Deploy to Firebase Hosting & Functions

on:
  push:
    branches:
      - deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            functions:
              - 'functions/**'
              - 'firebase.json'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: functions/package-lock.json

      - name: Install Functions Dependencies
        if: steps.changes.outputs.functions == 'true'
        run: npm ci
        working-directory: functions

      - name: Deploy Cloud Functions
        if: steps.changes.outputs.functions == 'true'
        run: npx firebase-tools deploy --only functions --project ${{ secrets.PROJECT_ID }} --force

      - name: Create firebaserc file
        run: |
          echo '{ "projects": { "default": "${{ secrets.PROJECT_ID }}" } }' > .firebaserc

      - name: Generate Firebase Config
        run: |
          mkdir -p public/js
          cat <<EOF > public/js/firebase-config.js
          export const firebaseConfig = {
            apiKey: "${{ secrets.API_KEY }}",
            authDomain: "${{ secrets.AUTH_DOMAIN }}",
            projectId: "${{ secrets.PROJECT_ID }}",
            storageBucket: "${{ secrets.STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.APP_ID }}",
            measurementId: "${{ secrets.MEASUREMENT_ID }}"
          };
          export const recaptchaSiteKey = "${{ secrets.RECAPTCHA_SITE_KEY }}";
          export const isLocalDevelopment = false;
          EOF

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live
          projectId: ${{ secrets.PROJECT_ID }}
